runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
  - url: /static
    static_dir: www/static/

  - url: /.*
    script: auto

env_variables:
  TRAVELER_PW: wishlist!!

beta_settings:
  cloud_sql_instances: wishlist-332314:us-central1:wishlist-db
