# Generated by Django 3.2.8 on 2021-11-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_catfact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatFact',
            new_name='CatFacts',
        ),
    ]
